POST http://localhost:3000/signin 
Content-Type: application/json

{
    "email": "jimi@gmail.com",
    "password": "Jimi@123"
}

# POST http://localhost:3000/signup 
# Content-Type: application/json

# {
#     "fullname": "jimi kumar",
#     "email":"jimmdfi@sasfdccsddf.com",
#     "password":"Jimi@123"
# }